const TESTNET = 'testnet'
const MAINNET = 'mainnet'
const LOCALHOST = 'localhost'

const MAINNET_CODE = 1
const TESTNET_CODE = 3

const TESTNET_DISPLAY_NAME = 'Testnet'
const RINKEBY_DISPLAY_NAME = 'Rinkeby'
const KOVAN_DISPLAY_NAME = 'Kovan'
const MAINNET_DISPLAY_NAME = 'Main Ethereum Network'

module.exports = {
  TESTNET,
  RINKEBY,
  KOVAN,
  MAINNET,
  LOCALHOST,
  GOERLI,
  MAINNET_CODE,
  TESTNET_CODE,
  RINKEBY_CODE,
  KOVAN_CODE,
  GOERLI_CODE,
  TESTNET_DISPLAY_NAME,
  RINKEBY_DISPLAY_NAME,
  KOVAN_DISPLAY_NAME,
  MAINNET_DISPLAY_NAME,
  GOERLI_DISPLAY_NAME,
}
